name: imgbb_downloader
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  flutter_inappwebview: ^6.0.0
  device_info_plus: ^9.1.2
  provider: ^6.1.2
  uuid: ^4.4.0
  file_picker: ^8.0.0+1
  shared_preferences: ^2.2.3
  image: ^4.0.17
  open_file: ^3.3.2
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1" # Add this line

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png" # You can point this to your highest resolution icon
  min_sdk_android: 21 # optional


flutter:
  uses-material-design: true