name: imgbb_downloader
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  flutter_inappwebview: ^6.0.0
  device_info_plus: ^9.1.2
  provider: ^6.1.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true